apiVersion: v1
kind: Service
metadata:
  name: node-app-service
  namespace: node-env

spec:
  selector:
    app: node-app-v1

  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000

  type: ClusterIP
